### PR TITLE
Move proto codec to separate Go module

### PR DESCRIPTION
**Pull request by philippgille**
Reasoning: To not force the proto transitive dependency on users who import the encoding package while only using stdlib codecs, as mentioned [here](https://github.com/philippgille/gokv/pull/127#pullrequestreview-1691437135).

### CODE REVIEW

**Comment by philippgille** [comment]
Cc @glimchb , is this okay for you?

**Comment by glimchb** [comment]
> Cc @glimchb , is this okay for you?

sure

**Comment by philippgille** [comment]
> sure. maybe just add quick example of new usage...

Good idea :+1: . I just created one and it works fine, but I'll submit that in a separate PR.

**Comment by philippgille** [comment]
PR for the code example: https://github.com/philippgille/gokv/pull/144

**Pull request merged**
